// <auto-generated />
namespace MvcFileManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeIsSearch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeIsSearch));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291451023_changeIsSearch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
