// <auto-generated />
namespace MvcFileManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changPM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changPM));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291447121_changPM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
