// <auto-generated />
namespace MvcFileManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class controllerupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(controllerupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201709230355447_controller update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
